version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: proxybroker serve --host 127.0.0.1 --port 8888 --types HTTP HTTPS --lvl High
          name: serve

workflows:
  main:
    jobs:
      - build-and-test
